export const ARTICLE_CATALOG = {
  "/ai/agents/agent-backend-architecture-map/": {
    "key": "agent-backend-architecture-map",
    "slug": "agent-backend-architecture-map",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-05",
    "title": "Agent Backend 한 장 지도: API, Queue, Worker, State, SSE는 어떻게 연결되는가",
    "path": "/ai/agents/agent-backend-architecture-map/"
  },
  "/ai/agents/agent-pattern-design/": {
    "key": "agent-pattern-design",
    "slug": "agent-pattern-design",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "에이전트 패턴 설계: Tool Use부터 Planner, Parallel, HITL, Reflection까지",
    "path": "/ai/agents/agent-pattern-design/"
  },
  "/ai/agents/agent-sse-streaming/": {
    "key": "agent-sse-streaming",
    "slug": "agent-sse-streaming",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Agent가 일하면서 말하게 하기: SSE, Generator, Redis Streams",
    "path": "/ai/agents/agent-sse-streaming/"
  },
  "/ai/agents/agent-tool-idempotency-approval-retry/": {
    "key": "agent-tool-idempotency-approval-retry",
    "slug": "agent-tool-idempotency-approval-retry",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-05",
    "title": "Agent Tool은 정확히 한 번 실행될 수 있을까: 승인, 멱등성, 재시도",
    "path": "/ai/agents/agent-tool-idempotency-approval-retry/"
  },
  "/ai/agents/async-thread-process-agent-backends/": {
    "key": "async-thread-process-agent-backends",
    "slug": "async-thread-process-agent-backends",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Async, Thread, Process: Agent Worker를 이해하기 전에 알아야 할 것",
    "path": "/ai/agents/async-thread-process-agent-backends/"
  },
  "/ai/ax/ax-is-transformation/": {
    "key": "ax-is-transformation",
    "slug": "ax-is-transformation",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "AX의 방점은 AI가 아니라 Transformation에 있다",
    "path": "/ai/ax/ax-is-transformation/"
  },
  "/ai/ax/ax-should-start-narrow/": {
    "key": "ax-should-start-narrow",
    "slug": "ax-should-start-narrow",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-21",
    "nextReviewDate": "2027-03-21",
    "title": "AX는 좁고 날카로워야 한다",
    "path": "/ai/ax/ax-should-start-narrow/"
  },
  "/ai/ax/from-retrieval-engineering-to-task-engineering/": {
    "key": "from-retrieval-engineering-to-task-engineering",
    "slug": "from-retrieval-engineering-to-task-engineering",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ai-agents",
      "rag",
      "evaluation",
      "enterprise-ai"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-12-28",
    "title": "Retrieval Engineering에서 Task Engineering으로",
    "path": "/ai/ax/from-retrieval-engineering-to-task-engineering/"
  },
  "/ai/agents/langgraph-runtime-not-architecture/": {
    "key": "langgraph-runtime-not-architecture",
    "slug": "langgraph-runtime-not-architecture",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-01-04",
    "title": "LangGraph는 Architecture가 아니다: Runtime의 정확한 위치",
    "path": "/ai/agents/langgraph-runtime-not-architecture/"
  },
  "/ai/agents/state-is-not-event/": {
    "key": "state-is-not-event",
    "slug": "state-is-not-event",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "State는 Event가 아니다: 실시간 Agent UI 설계법",
    "path": "/ai/agents/state-is-not-event/"
  },
  "/ai/ai-engineering/vllm-troubleshooting-metrics/": {
    "key": "vllm-troubleshooting-metrics",
    "slug": "vllm-troubleshooting-metrics",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "implementation",
    "topics": [
      "enterprise-ai",
      "evaluation",
      "ai-agents"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-09-22",
    "nextReviewDate": "2026-12-22",
    "title": "vLLM은 왜 느려졌을까?",
    "path": "/ai/ai-engineering/vllm-troubleshooting-metrics/"
  },
  "/ai/ai-engineering/vllm-tuning-limited-gpus/": {
    "key": "vllm-tuning-limited-gpus",
    "slug": "vllm-tuning-limited-gpus",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "implementation",
    "topics": [
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-09-20",
    "nextReviewDate": "2026-12-20",
    "title": "vLLM 튜닝이란 무엇인가?",
    "path": "/ai/ai-engineering/vllm-tuning-limited-gpus/"
  },
  "/ai/ax/we-built-the-agent-platform-too-early/": {
    "key": "we-built-the-agent-platform-too-early",
    "slug": "we-built-the-agent-platform-too-early",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "perspective",
    "topics": [
      "ai-agents",
      "enterprise-ai",
      "ax",
      "evaluation"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-09-29",
    "nextReviewDate": "2027-03-29",
    "title": "우리의 에이전트 플랫폼은 왜 처음엔 삐걱댔을까",
    "path": "/ai/ax/we-built-the-agent-platform-too-early/"
  },
  "/ai/agents/where-agent-state-lives/": {
    "key": "where-agent-state-lives",
    "slug": "where-agent-state-lives",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Agent State는 어디에 있어야 하는가: PostgreSQL, Redis, Checkpoint",
    "path": "/ai/agents/where-agent-state-lives/"
  },
  "/ai/ax/who-disappears-first-ai-or-business-teams/": {
    "key": "who-disappears-first-ai-or-business-teams",
    "slug": "who-disappears-first-ai-or-business-teams",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-26",
    "nextReviewDate": "2027-03-26",
    "title": "AI팀과 현업, 누가 먼저 사라질까?",
    "path": "/ai/ax/who-disappears-first-ai-or-business-teams/"
  },
  "/ai/agents/why-agent-systems-need-async/": {
    "key": "why-agent-systems-need-async",
    "slug": "why-agent-systems-need-async",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "에이전트는 왜 Async가 필요한가: 기다리는 동안 다른 일을 시키는 법",
    "path": "/ai/agents/why-agent-systems-need-async/"
  },
  "/ai/ax/why-i-am-removing-langgraph-from-agent-building/": {
    "key": "why-i-am-removing-langgraph-from-agent-building",
    "slug": "why-i-am-removing-langgraph-from-agent-building",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "perspective",
    "topics": [
      "ai-agents",
      "langgraph",
      "ax"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-09-26",
    "nextReviewDate": "2026-12-26",
    "title": "에이전트는 꼭 그래프여야 할까 — 내가 LangGraph를 걷어내기 시작한 이유",
    "path": "/ai/ax/why-i-am-removing-langgraph-from-agent-building/"
  },
  "/ai/ai-engineering/why-vllm-for-internal-llm-serving/": {
    "key": "why-vllm-for-internal-llm-serving",
    "slug": "why-vllm-for-internal-llm-serving",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "foundation",
    "topics": [
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-12-05",
    "title": "왜 내부 GPU에서 vLLM으로 LLM을 서빙하는가?",
    "path": "/ai/ai-engineering/why-vllm-for-internal-llm-serving/"
  },
  "/ai/agents/worker-is-not-thread/": {
    "key": "worker-is-not-thread",
    "slug": "worker-is-not-thread",
    "language": "ko",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "Worker는 Thread가 아니다: Agent 실행을 API 서버에서 분리하는 이유",
    "path": "/ai/agents/worker-is-not-thread/"
  },
  "/coding/experiments/ai-handoff-queue-lab/": {
    "key": "ai-handoff-queue-lab",
    "slug": "ai-handoff-queue-lab",
    "language": "ko",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "AI 이관 대기열 시뮬레이터",
    "path": "/coding/experiments/ai-handoff-queue-lab/"
  },
  "/coding/experiments/huntington-ingalls-industries-valuation-lab/": {
    "key": "huntington-ingalls-industries-valuation-lab",
    "slug": "huntington-ingalls-industries-valuation-lab",
    "language": "ko",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-08",
    "nextReviewDate": "2026-11-16",
    "title": "Huntington Ingalls Industries Valuation Lab: 7.5% 마진을 직접 바꿔보면",
    "path": "/coding/experiments/huntington-ingalls-industries-valuation-lab/"
  },
  "/coding/experiments/poisson-demand-inventory-lab/": {
    "key": "poisson-demand-inventory-lab",
    "slug": "poisson-demand-inventory-lab",
    "language": "ko",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": "- supply-chain",
    "primaryTopic": "supply-chain",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-01",
    "nextReviewDate": "2027-10-01",
    "title": "푸아송 수요·재고 시뮬레이터",
    "path": "/coding/experiments/poisson-demand-inventory-lab/"
  },
  "/coding/experiments/samsung-earnings-event-lab/": {
    "key": "samsung-earnings-event-lab",
    "slug": "samsung-earnings-event-lab",
    "language": "ko",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "research",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-09-27",
    "nextReviewDate": "2026-10-27",
    "title": "실적은 예상보다 좋았는데, 주가는 왜 떨어졌을까?",
    "path": "/coding/experiments/samsung-earnings-event-lab/"
  },
  "/coding/experiments/sterling-infrastructure-valuation-lab/": {
    "key": "sterling-infrastructure-valuation-lab",
    "slug": "sterling-infrastructure-valuation-lab",
    "language": "ko",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-07",
    "nextReviewDate": "2026-11-16",
    "title": "Sterling Infrastructure Valuation Lab: 현재 주가가 요구하는 성장률",
    "path": "/coding/experiments/sterling-infrastructure-valuation-lab/"
  },
  "/en/ai/agents/agent-backend-architecture-map/": {
    "key": "agent-backend-architecture-map",
    "slug": "agent-backend-architecture-map",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-05",
    "title": "Agent Backend Architecture at a Glance: How APIs, Queues, Workers, State, and SSE Fit Together",
    "path": "/en/ai/agents/agent-backend-architecture-map/"
  },
  "/en/ai/agents/agent-pattern-design/": {
    "key": "agent-pattern-design",
    "slug": "agent-pattern-design",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "Agent Pattern Design: From Tool Use to Planning, Parallelism, HITL, and Reflection",
    "path": "/en/ai/agents/agent-pattern-design/"
  },
  "/en/ai/agents/agent-sse-streaming/": {
    "key": "agent-sse-streaming",
    "slug": "agent-sse-streaming",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Let the Agent Speak While It Works: SSE, Generators, and Redis Streams",
    "path": "/en/ai/agents/agent-sse-streaming/"
  },
  "/en/ai/agents/agent-tool-idempotency-approval-retry/": {
    "key": "agent-tool-idempotency-approval-retry",
    "slug": "agent-tool-idempotency-approval-retry",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-05",
    "title": "Can an Agent Tool Execute Exactly Once? Approval, Idempotency, and Retries",
    "path": "/en/ai/agents/agent-tool-idempotency-approval-retry/"
  },
  "/en/ai/agents/async-thread-process-agent-backends/": {
    "key": "async-thread-process-agent-backends",
    "slug": "async-thread-process-agent-backends",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Async, Threads, and Processes: What to Know Before Agent Workers",
    "path": "/en/ai/agents/async-thread-process-agent-backends/"
  },
  "/en/ai/ax/ax-is-transformation/": {
    "key": "ax-is-transformation",
    "slug": "ax-is-transformation",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "The Point of AX Is Transformation, Not AI",
    "path": "/en/ai/ax/ax-is-transformation/"
  },
  "/en/ai/ax/ax-should-start-narrow/": {
    "key": "ax-should-start-narrow",
    "slug": "ax-should-start-narrow",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-21",
    "nextReviewDate": "2027-03-21",
    "title": "Why Enterprise AI Transformation Should Start Narrow",
    "path": "/en/ai/ax/ax-should-start-narrow/"
  },
  "/en/ai/ax/from-retrieval-engineering-to-task-engineering/": {
    "key": "from-retrieval-engineering-to-task-engineering",
    "slug": "from-retrieval-engineering-to-task-engineering",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ai-agents",
      "rag",
      "evaluation",
      "enterprise-ai"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-12-28",
    "title": "From Retrieval Engineering to Task Engineering",
    "path": "/en/ai/ax/from-retrieval-engineering-to-task-engineering/"
  },
  "/en/ai/agents/langgraph-runtime-not-architecture/": {
    "key": "langgraph-runtime-not-architecture",
    "slug": "langgraph-runtime-not-architecture",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-01-04",
    "title": "LangGraph Is Not Architecture: Where the Runtime Actually Belongs",
    "path": "/en/ai/agents/langgraph-runtime-not-architecture/"
  },
  "/en/ai/agents/state-is-not-event/": {
    "key": "state-is-not-event",
    "slug": "state-is-not-event",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "State Is Not an Event: Designing Real-Time Agent UIs",
    "path": "/en/ai/agents/state-is-not-event/"
  },
  "/en/ai/ai-engineering/vllm-troubleshooting-metrics/": {
    "key": "vllm-troubleshooting-metrics",
    "slug": "vllm-troubleshooting-metrics",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "implementation",
    "topics": [
      "enterprise-ai",
      "evaluation",
      "ai-agents"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-09-22",
    "nextReviewDate": "2026-12-22",
    "title": "Why Is vLLM Slow?",
    "path": "/en/ai/ai-engineering/vllm-troubleshooting-metrics/"
  },
  "/en/ai/ai-engineering/vllm-tuning-limited-gpus/": {
    "key": "vllm-tuning-limited-gpus",
    "slug": "vllm-tuning-limited-gpus",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "implementation",
    "topics": [
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-09-20",
    "nextReviewDate": "2026-12-20",
    "title": "What is vLLM tuning?",
    "path": "/en/ai/ai-engineering/vllm-tuning-limited-gpus/"
  },
  "/en/ai/ax/we-built-the-agent-platform-too-early/": {
    "key": "we-built-the-agent-platform-too-early",
    "slug": "we-built-the-agent-platform-too-early",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "perspective",
    "topics": [
      "ai-agents",
      "enterprise-ai",
      "ax",
      "evaluation"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-09-29",
    "nextReviewDate": "2027-03-29",
    "title": "Why Our Agent Platform Got Off to a Rocky Start",
    "path": "/en/ai/ax/we-built-the-agent-platform-too-early/"
  },
  "/en/ai/agents/where-agent-state-lives/": {
    "key": "where-agent-state-lives",
    "slug": "where-agent-state-lives",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Where Does Agent State Live? Redis, PostgreSQL, and Checkpoints",
    "path": "/en/ai/agents/where-agent-state-lives/"
  },
  "/en/ai/ax/who-disappears-first-ai-or-business-teams/": {
    "key": "who-disappears-first-ai-or-business-teams",
    "slug": "who-disappears-first-ai-or-business-teams",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "research",
    "topics": [
      "ax",
      "enterprise-ai",
      "ai-agents"
    ],
    "primaryTopic": "ax",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-26",
    "nextReviewDate": "2027-03-26",
    "title": "Who Disappears First: The AI Team or the Business Teams?",
    "path": "/en/ai/ax/who-disappears-first-ai-or-business-teams/"
  },
  "/en/ai/agents/why-agent-systems-need-async/": {
    "key": "why-agent-systems-need-async",
    "slug": "why-agent-systems-need-async",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2027-10-04",
    "title": "Why Agent Systems Need Async: Making Waiting Time Useful",
    "path": "/en/ai/agents/why-agent-systems-need-async/"
  },
  "/en/ai/ax/why-i-am-removing-langgraph-from-agent-building/": {
    "key": "why-i-am-removing-langgraph-from-agent-building",
    "slug": "why-i-am-removing-langgraph-from-agent-building",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AX",
    "contentType": "perspective",
    "topics": [
      "ai-agents",
      "langgraph",
      "ax"
    ],
    "primaryTopic": "ai-agents",
    "freshness": "periodic",
    "lastReviewed": "2026-09-26",
    "nextReviewDate": "2026-12-26",
    "title": "Do Agents Have to Be Graphs? Why I Am Removing LangGraph from My Default Stack",
    "path": "/en/ai/ax/why-i-am-removing-langgraph-from-agent-building/"
  },
  "/en/ai/ai-engineering/why-vllm-for-internal-llm-serving/": {
    "key": "why-vllm-for-internal-llm-serving",
    "slug": "why-vllm-for-internal-llm-serving",
    "language": "en",
    "section": "AI & AX",
    "subsection": "AI Engineering",
    "contentType": "foundation",
    "topics": [
      "enterprise-ai",
      "ai-agents",
      "evaluation"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-12-05",
    "title": "Why Serve Open-Source LLMs with vLLM on Internal GPUs?",
    "path": "/en/ai/ai-engineering/why-vllm-for-internal-llm-serving/"
  },
  "/en/ai/agents/worker-is-not-thread/": {
    "key": "worker-is-not-thread",
    "slug": "worker-is-not-thread",
    "language": "en",
    "section": "AI & AX",
    "subsection": "Agents",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "A Worker Is Not a Thread: Why Agent Execution Should Leave the API Server",
    "path": "/en/ai/agents/worker-is-not-thread/"
  },
  "/en/coding/experiments/ai-handoff-queue-lab/": {
    "key": "ai-handoff-queue-lab",
    "slug": "ai-handoff-queue-lab",
    "language": "en",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-04",
    "nextReviewDate": "2027-10-04",
    "title": "AI Handoff Queue Simulator",
    "path": "/en/coding/experiments/ai-handoff-queue-lab/"
  },
  "/en/coding/experiments/huntington-ingalls-industries-valuation-lab/": {
    "key": "huntington-ingalls-industries-valuation-lab",
    "slug": "huntington-ingalls-industries-valuation-lab",
    "language": "en",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-08",
    "nextReviewDate": "2026-11-16",
    "title": "Huntington Ingalls Industries Valuation Lab: Stress-Test the 7.5% Margin",
    "path": "/en/coding/experiments/huntington-ingalls-industries-valuation-lab/"
  },
  "/en/coding/experiments/poisson-demand-inventory-lab/": {
    "key": "poisson-demand-inventory-lab",
    "slug": "poisson-demand-inventory-lab",
    "language": "en",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": "- supply-chain",
    "primaryTopic": "supply-chain",
    "freshness": "evergreen",
    "lastReviewed": "2026-10-01",
    "nextReviewDate": "2027-10-01",
    "title": "Poisson Demand and Inventory Simulator",
    "path": "/en/coding/experiments/poisson-demand-inventory-lab/"
  },
  "/en/coding/experiments/samsung-earnings-event-lab/": {
    "key": "samsung-earnings-event-lab",
    "slug": "samsung-earnings-event-lab",
    "language": "en",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "research",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-09-27",
    "nextReviewDate": "2026-10-27",
    "title": "A Profit Beat, a Falling Stock: What Can the Data Tell Us?",
    "path": "/en/coding/experiments/samsung-earnings-event-lab/"
  },
  "/en/coding/experiments/sterling-infrastructure-valuation-lab/": {
    "key": "sterling-infrastructure-valuation-lab",
    "slug": "sterling-infrastructure-valuation-lab",
    "language": "en",
    "section": "Lab",
    "subsection": "Experiments",
    "contentType": "implementation",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-07",
    "nextReviewDate": "2026-11-16",
    "title": "Sterling Infrastructure Valuation Lab: The Growth Implied by Today’s Price",
    "path": "/en/coding/experiments/sterling-infrastructure-valuation-lab/"
  },
  "/en/investing/markets/efficient-markets-bayesian-lens/": {
    "key": "efficient-markets-bayesian-lens",
    "slug": "efficient-markets-bayesian-lens",
    "language": "en",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-09-27",
    "nextReviewDate": "2026-10-27",
    "title": "Efficient Markets Through a Bayesian Lens: Why Does Everything Seem Priced In?",
    "path": "/en/investing/markets/efficient-markets-bayesian-lens/"
  },
  "/en/investing/research/fde-economics-wonderful-reflection/": {
    "key": "fde-economics-wonderful-reflection",
    "slug": "fde-economics-wonderful-reflection",
    "language": "en",
    "section": "Investing",
    "subsection": "Research",
    "contentType": "research",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-02",
    "nextReviewDate": "2026-11-02",
    "title": "FDE Economics: What Wonderful and Reflection Need to Prove",
    "path": "/en/investing/research/fde-economics-wonderful-reflection/"
  },
  "/en/investing/research/fde-loop-hyperscalers-palantir/": {
    "key": "fde-loop-hyperscalers-palantir",
    "slug": "fde-loop-hyperscalers-palantir",
    "language": "en",
    "section": "Investing",
    "subsection": "Research",
    "contentType": "research",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-03",
    "nextReviewDate": "2026-11-03",
    "title": "AWS Is Hiring FDEs. But Can You Hire Your Way Into an FDE Organization?",
    "path": "/en/investing/research/fde-loop-hyperscalers-palantir/"
  },
  "/en/investing/markets/huntington-ingalls-industries-valuation/": {
    "key": "huntington-ingalls-industries-valuation",
    "slug": "huntington-ingalls-industries-valuation",
    "language": "en",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-08",
    "nextReviewDate": "2026-11-16",
    "title": "Huntington Ingalls Industries: Why Does a Monopoly Shipbuilder With $57 Billion of Orders Trade at 14×?",
    "path": "/en/investing/markets/huntington-ingalls-industries-valuation/"
  },
  "/en/investing/markets/sterling-infrastructure-fair-value/": {
    "key": "sterling-infrastructure-fair-value",
    "slug": "sterling-infrastructure-fair-value",
    "language": "en",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-07",
    "nextReviewDate": "2026-11-16",
    "title": "Sterling Infrastructure: Time to Sell? A Good Company, but About Fair Value Now",
    "path": "/en/investing/markets/sterling-infrastructure-fair-value/"
  },
  "/en/investing/markets/will-rogo-eat-financial-ai/": {
    "key": "will-rogo-eat-financial-ai",
    "slug": "will-rogo-eat-financial-ai",
    "language": "en",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "enterprise-ai",
      "portfolio"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-11-03",
    "title": "Will Rogo Eat the Financial Intelligence Stack? Two Years with AlphaSense Changed My Answer",
    "path": "/en/investing/markets/will-rogo-eat-financial-ai/"
  },
  "/en/math/statistics/bayesian-statistics-dog-walk/": {
    "key": "bayesian-statistics-dog-walk",
    "slug": "bayesian-statistics-dog-walk",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "What Is Bayesian Statistics?",
    "path": "/en/math/statistics/bayesian-statistics-dog-walk/"
  },
  "/en/math/statistics/exponential-distribution-ai-handoff/": {
    "key": "exponential-distribution-ai-handoff",
    "slug": "exponential-distribution-ai-handoff",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-10-03",
    "nextReviewDate": "2027-04-03",
    "title": "What Is the Exponential Distribution?",
    "path": "/en/math/statistics/exponential-distribution-ai-handoff/"
  },
  "/en/math/optimization/multi-objective-optimization-battery-supply-chain/": {
    "key": "multi-objective-optimization-battery-supply-chain",
    "slug": "multi-objective-optimization-battery-supply-chain",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "multi-objective-optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "What is multi-objective optimization?",
    "path": "/en/math/optimization/multi-objective-optimization-battery-supply-chain/"
  },
  "/en/math/optimization/pareto-optimization-dinner-with-friends/": {
    "key": "pareto-optimization-dinner-with-friends",
    "slug": "pareto-optimization-dinner-with-friends",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "What is Pareto optimization?",
    "path": "/en/math/optimization/pareto-optimization-dinner-with-friends/"
  },
  "/en/math/statistics/poisson-demand-inventory/": {
    "key": "poisson-demand-inventory",
    "slug": "poisson-demand-inventory",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- supply-chain",
    "primaryTopic": "supply-chain",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-30",
    "nextReviewDate": "2027-09-30",
    "title": "What Is the Poisson Distribution?",
    "path": "/en/math/statistics/poisson-demand-inventory/"
  },
  "/en/math/optimization/what-is-optimization-dinner-with-friends/": {
    "key": "what-is-optimization-dinner-with-friends",
    "slug": "what-is-optimization-dinner-with-friends",
    "language": "en",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "What is optimization?",
    "path": "/en/math/optimization/what-is-optimization-dinner-with-friends/"
  },
  "/en/misc/essays/why-this-archive-is-open/": {
    "key": "why-this-archive-is-open",
    "slug": "why-this-archive-is-open",
    "language": "en",
    "section": "Perspectives",
    "subsection": "Essays",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-01",
    "nextReviewDate": "2027-03-01",
    "title": "Why I Keep Research as an Archive, Not a Feed",
    "path": "/en/misc/essays/why-this-archive-is-open/"
  },
  "/investing/markets/efficient-markets-bayesian-lens/": {
    "key": "efficient-markets-bayesian-lens",
    "slug": "efficient-markets-bayesian-lens",
    "language": "ko",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-09-27",
    "nextReviewDate": "2026-10-27",
    "title": "베이즈의 렌즈로 보는 효율적 시장가설: '킹반영'은 왜 계속 일어날까?",
    "path": "/investing/markets/efficient-markets-bayesian-lens/"
  },
  "/investing/research/fde-economics-wonderful-reflection/": {
    "key": "fde-economics-wonderful-reflection",
    "slug": "fde-economics-wonderful-reflection",
    "language": "ko",
    "section": "Investing",
    "subsection": "Research",
    "contentType": "research",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-02",
    "nextReviewDate": "2026-11-02",
    "title": "FDE는 SI의 새 이름일까? Wonderful과 Reflection의 밸류에이션이 묻는 것",
    "path": "/investing/research/fde-economics-wonderful-reflection/"
  },
  "/investing/research/fde-loop-hyperscalers-palantir/": {
    "key": "fde-loop-hyperscalers-palantir",
    "slug": "fde-loop-hyperscalers-palantir",
    "language": "ko",
    "section": "Investing",
    "subsection": "Research",
    "contentType": "research",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-03",
    "nextReviewDate": "2026-11-03",
    "title": "AWS도 FDE를 뽑기 시작했다. 그런데 FDE는 채용한다고 만들어질까?",
    "path": "/investing/research/fde-loop-hyperscalers-palantir/"
  },
  "/investing/markets/huntington-ingalls-industries-valuation/": {
    "key": "huntington-ingalls-industries-valuation",
    "slug": "huntington-ingalls-industries-valuation",
    "language": "ko",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-08",
    "nextReviewDate": "2026-11-16",
    "title": "Huntington Ingalls Industries: 570억 달러의 주문을 가진 독점 조선소는 왜 14배에 거래될까?",
    "path": "/investing/markets/huntington-ingalls-industries-valuation/"
  },
  "/investing/markets/sterling-infrastructure-fair-value/": {
    "key": "sterling-infrastructure-fair-value",
    "slug": "sterling-infrastructure-fair-value",
    "language": "ko",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "portfolio",
      "supply-chain"
    ],
    "primaryTopic": "portfolio",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-07",
    "nextReviewDate": "2026-11-16",
    "title": "Sterling Infrastructure: 이제 팔고 나가야 할 주식? 좋은 회사지만 지금은 적정가 수준이다",
    "path": "/investing/markets/sterling-infrastructure-fair-value/"
  },
  "/investing/markets/will-rogo-eat-financial-ai/": {
    "key": "will-rogo-eat-financial-ai",
    "slug": "will-rogo-eat-financial-ai",
    "language": "ko",
    "section": "Investing",
    "subsection": "Markets",
    "contentType": "research",
    "topics": [
      "enterprise-ai",
      "portfolio"
    ],
    "primaryTopic": "enterprise-ai",
    "freshness": "time-sensitive",
    "lastReviewed": "2026-10-05",
    "nextReviewDate": "2026-11-03",
    "title": "Rogo가 금융 AI를 다 먹어버릴까? AlphaSense를 2년 써보며 생각한 데이터의 해자",
    "path": "/investing/markets/will-rogo-eat-financial-ai/"
  },
  "/math/statistics/bayesian-statistics-dog-walk/": {
    "key": "bayesian-statistics-dog-walk",
    "slug": "bayesian-statistics-dog-walk",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- bayesian-inference",
    "primaryTopic": "bayesian-inference",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "베이즈 통계학이란 무엇인가?",
    "path": "/math/statistics/bayesian-statistics-dog-walk/"
  },
  "/math/statistics/exponential-distribution-ai-handoff/": {
    "key": "exponential-distribution-ai-handoff",
    "slug": "exponential-distribution-ai-handoff",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- enterprise-ai",
    "primaryTopic": "enterprise-ai",
    "freshness": "periodic",
    "lastReviewed": "2026-10-03",
    "nextReviewDate": "2027-04-03",
    "title": "지수분포란 무엇인가?",
    "path": "/math/statistics/exponential-distribution-ai-handoff/"
  },
  "/math/optimization/multi-objective-optimization-battery-supply-chain/": {
    "key": "multi-objective-optimization-battery-supply-chain",
    "slug": "multi-objective-optimization-battery-supply-chain",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "multi-objective-optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "다목적 최적화란 무엇인가?",
    "path": "/math/optimization/multi-objective-optimization-battery-supply-chain/"
  },
  "/math/optimization/pareto-optimization-dinner-with-friends/": {
    "key": "pareto-optimization-dinner-with-friends",
    "slug": "pareto-optimization-dinner-with-friends",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "파레토 최적화란 무엇인가?",
    "path": "/math/optimization/pareto-optimization-dinner-with-friends/"
  },
  "/math/statistics/poisson-demand-inventory/": {
    "key": "poisson-demand-inventory",
    "slug": "poisson-demand-inventory",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Statistics",
    "contentType": "foundation",
    "topics": "- supply-chain",
    "primaryTopic": "supply-chain",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-30",
    "nextReviewDate": "2027-09-30",
    "title": "푸아송 분포란 무엇인가?",
    "path": "/math/statistics/poisson-demand-inventory/"
  },
  "/math/optimization/what-is-optimization-dinner-with-friends/": {
    "key": "what-is-optimization-dinner-with-friends",
    "slug": "what-is-optimization-dinner-with-friends",
    "language": "ko",
    "section": "Mathematics",
    "subsection": "Optimization",
    "contentType": "foundation",
    "topics": "- optimization",
    "primaryTopic": "optimization",
    "freshness": "evergreen",
    "lastReviewed": null,
    "nextReviewDate": null,
    "title": "최적화란 무엇인가?",
    "path": "/math/optimization/what-is-optimization-dinner-with-friends/"
  },
  "/misc/essays/why-this-archive-is-open/": {
    "key": "why-this-archive-is-open",
    "slug": "why-this-archive-is-open",
    "language": "ko",
    "section": "Perspectives",
    "subsection": "Essays",
    "contentType": "foundation",
    "topics": "- ai-agents",
    "primaryTopic": "ai-agents",
    "freshness": "evergreen",
    "lastReviewed": "2026-09-01",
    "nextReviewDate": "2027-03-01",
    "title": "왜 리서치를 피드가 아니라 아카이브로 남기는가",
    "path": "/misc/essays/why-this-archive-is-open/"
  }
};
